#ifndef NOVELVIEWCORE_GLOBAL_HPP
#define NOVELVIEWCORE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(NOVELVIEWCORE_LIBRARY)
#  define NOVELVIEWCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NOVELVIEWCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NOVELVIEWCORE_GLOBAL_HPP
